---
- name: Prepare default fragments
  copy:
    src: '{{ item[1] }}'
    dest: /etc/iptables/fragments.{{ item[0] }}/{{ item[1] }}
    owner: root
    group: root
    mode: 0644
  loop: "{{ lookup('nested', ['v4', 'v6'], ['00_header', '99_footer']) }}"

- name: Generate v4 rules
  assemble:
    src: /etc/iptables/fragments.v4
    dest: '{{ iptables_rulesfile_v4 }}'
    backup: true
    owner: root
    group: root
    mode: 0644
  register: r_rulefile_v4
- name: Generate v6 rules
  assemble:
    src: /etc/iptables/fragments.v6
    dest: '{{ iptables_rulesfile_v6 }}'
    backup: true
    owner: root
    group: root
    mode: 0644
  register: r_rulefile_v6

- name: Reload iptables rules
  shell: iptables-restore < {{ iptables_rulesfile_v4 }}
  when: r_rulefile_v4 is changed

- name: Reload ip6tables rules
  shell: ip6tables-restore < {{ iptables_rulesfile_v6 }}
  when: r_rulefile_v6 is changed
