---
- name: Install iptables persistence package
  package:
    name: '{{ iptables_persistence_package }}'

- name: Enable iptables services
  service:
    name: '{{ item }}'
    enabled: true
  loop: '{{ iptables_services }}'

- name: Create iptables fragment dirs
  file:
    path: /etc/iptables/fragments.{{ item }}
    state: directory
    owner: root
    group: root
  loop:
    - v4
    - v6
